import json

try:
    with open('mercy.json', 'r', encoding='utf-8') as f:
        products = json.load(f)

    with open('mercy_data.sql', 'w', encoding='utf-8') as f:
        f.write("""CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria TEXT NOT NULL,
  nombre TEXT NOT NULL,
  precio NUMERIC(10, 2) DEFAULT 1.00,
  disponible BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

""")
        
        f.write("INSERT INTO productos (categoria, nombre, precio, disponible) VALUES\n")
        
        inserts = []
        for p in products:
            categoria = p['Categoria'].replace("'", "''")
            nombre = p['Nombre'].replace("'", "''")
            precio = p.get('Precio (CUP)', 1.00)
            # Como disponible era null en el excel, le ponemos TRUE por defecto
            disponible = 'TRUE'
            inserts.append(f"('{categoria}', '{nombre}', {precio}, {disponible})")
            
        f.write(",\n".join(inserts) + ";\n")

    print("Archivo mercy_data.sql creado con éxito.")
except Exception as e:
    print("Error:", e)
